### ISSUE TITLE
Editor

### ISSUE THREAD

**Issue by shaedrich** [shaedrich/github-uncurated-topics#10]
# Current behavior
Currently, you create all information of a topic by creating a new markdown file with YAML frontmatter. Validation and autocompletion can only be done via GitHub actions and their results need to understood in case of errors.

# Intended behavior
With a view like the actual topic page, including a form with separate input for each information, validation and autocompletion can be done in place for a more rich editing experience.

# Tasks
- [ ] Autocompletion and multi selects
- [ ] Validation rules
    - [ ] static
    - [ ] API
- [x] [Primer layout and design](https://primer.style/design/)
- [ ] API request to save
